### PR TITLE
Fix missing fetch

### LINKED ISSUE #106: git clone/checkout fails when using commit sha1 as tag
Currently we need to fork [Schedul-o-matic-9000](https://github.com/pmd/Schedul-o-matic-9000) and [fflib-apex-common](https://github.com/pmd/fflib-apex-common) in order to create a tag, that we can use in [project-list.xml](https://github.com/pmd/pmd/blob/master/.ci/files/project-list.xml):

```xml
  <project>
    <name>Schedul-o-matic-9000</name>
    <type>git</type>
    <connection>https://github.com/pmd/Schedul-o-matic-9000</connection>
    <!-- 
    <connection>https://github.com/SalesforceLabs/Schedul-o-matic-9000</connection>
    Note: using forked repo from pmd, as original repo doesn't have any useful tags/branches
    -->
    <tag>pmd-regression-test</tag>
  </project>
```

It would be nice to allow to specify directly a sha1 for the commit, e.g.

```xml
  <project>
    <name>Schedul-o-matic-9000</name>
    <type>git</type>
    <connection>https://github.com/SalesforceLabs/Schedul-o-matic-9000</connection>
    <tag>6b1229ba43b38931fbbab5924bc9b9611d19a786</tag>
  </project>
```

Using the `tag`-tag would avoid to change the schema for this file.

### PR DESCRIPTION
**Pull request by oowekyala**
Fix #106 

Ref problems in pmd/pmd#3960

### CODE REVIEW

File: lib/pmdtester/builders/project_builder.rb [hunk 1]
```diff
@@ -19,22 +19,22 @@ def clone_projects
...
-
+          # Don't download whole history. This just fetches HEAD, the correct ref is fetched below.
+          clone_cmd = "git clone --single-branch --depth 1 #{project.connection} #{path}"
           Cmd.execute_successfully(clone_cmd)
         end
 
         Dir.chdir(path) do
-          execute_reset_cmd(project.type, project.tag)
+          # this should work with tags, branch names and (full-length) hashes
+          Cmd.execute_successfully("git fetch --depth 1 origin #{tag}")
```
Comment (oowekyala) [inline lib/pmdtester/builders/project_builder.rb:36]: note: i haven't actually checked whether this works for tags. the proper syntax is maybe `tags/tagname`

Comment (oowekyala) [reply lib/pmdtester/builders/project_builder.rb:36]: See https://stackoverflow.com/questions/45338495/fetch-a-single-tag-from-remote-repository

Comment (adangel) [reply lib/pmdtester/builders/project_builder.rb:36]: I'll look at this - I like the idea to use a fetch here. This will make it easier to reuse the clones, even if upstream changes.
